INSERT INTO property_types (CREATED_AT, LAST_MODIFIED_AT, VERSION, NAME, PRIORITY)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'residential', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'land', 3),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'commercial', 2);


INSERT INTO property_categories (CREATED_AT, LAST_MODIFIED_AT, VERSION, ICON, NAME, FK_TYPE_ID, PRIORITY)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'apartment', 'apartment', 1, 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'home', 'house', 1, 3),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'room', 'room', 1, 2),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'townHouse', 'townHouseDuplex', 1, 4),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'resortHouse', 'resortHouse', 1, 5),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'mall', 'commercialEstate', 3, 2),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'garage', 'garage', 3, 3),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'townHouse', 'commercialFreePurpose', 3, 4),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'briefcase', 'office', 3, 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'farm', 'agriculturalLand', 2, 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'commercial', 'commercialLand', 2, 2),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'inConstruction', 'underConstructionLand', 2, 3)
;

INSERT INTO configuration_categories (CREATED_AT, LAST_MODIFIED_AT, VERSION, ICON, NAME, PRIORITY,
                                      IS_ONLY_FOR_RENT, IS_DETAILED)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'property', 1, false, false),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'configuration', 'configuration', 2, false, false),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'tenant', 'tenant', 3, true, false),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'pet', 'pets', 4, true, false),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'time', 'period', 5, true, false),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'price', 'price', 6, false, false),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'handshake', 'underRedemption', 7, false, false),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'house', 'comfort', 8, false, true),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'eye', 'yardType', 9, false, true),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'wallHeight', 'wallHeight', 10, false, true),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'infrastructure', 'infrastructure', 11, false, true),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'security', 'security', 12, false, true),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'house', 'purposeCategory', 0, false, false)
;

INSERT INTO configuration_types (CREATED_AT, LAST_MODIFIED_AT, VERSION, NAME)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'range'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'date'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'distance'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'time'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'select'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'check'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'priority'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'prioritySlider'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'price');


INSERT INTO configurations (CREATED_AT, LAST_MODIFIED_AT, VERSION, ICON, NAME, FK_CATEGORY_ID, FK_TYPE_ID,
                            IS_ICON_LARGE, PRIORITY, IS_HEADER, IS_SPECIAL)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'apartment', 'propertyType', 1, 7, FALSE, 1, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'wall', 'wallType', 1, 7, FALSE, 2, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'puzzle', 'planning', 2, 7, FALSE, 1, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'room', 'room', 2, 7, FALSE, 2, TRUE, TRUE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'area', 'area', 2, 1, FALSE, 3, TRUE, TRUE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ladder', 'storeys', 2, 1, FALSE, 4, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'heater', 'heating', 2, 7, FALSE, 5, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'bathroom', 'restroom', 2, 7, FALSE, 6, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'repair', 'repaired', 2, 7, FALSE, 7, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'furniture', 'furniture', 2, 8, FALSE, 8, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'tenants', 3, 5, TRUE, 9, FALSE, TRUE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'pets', 4, 5, FALSE, 10, FALSE, TRUE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'hourglass', 'period', 5, 5, FALSE, 11, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'calendar', 'readyForArrival', 5, 2, FALSE, 12, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'price', 6, 9, FALSE, 13, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'handshake', 'underRedemption', 7, 6, FALSE, 14, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'boiler', 'boiler', 8, 6, TRUE, 15, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'oven', 'oven', 8, 6, TRUE, 16, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'infrastructure', 'infrastructure', 11, 4, TRUE, 17, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'communal', 2, 3, FALSE, 18, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'airConditioner', 'airConditioner', 8, 6, TRUE, 19, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'wifi', 'wifi', 8, 6, TRUE, 20, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'tub', 'tub', 8, 6, TRUE, 21, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'bath', 'bath', 8, 6, TRUE, 22, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'balcony', 'balcony', 8, 6, TRUE, 23, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'terrace', 'terrace', 8, 6, TRUE, 24, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'parking', 'parking', 8, 6, TRUE, 25, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'window', 'panoramic', 8, 6, TRUE, 26, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'alarm', 'alarm', 8, 6, TRUE, 27, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'closet', 'wardrobe', 8, 6, TRUE, 28, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'bed', 'bed', 8, 6, TRUE, 29, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'sofa', 'sofa', 8, 6, TRUE, 30, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'bedOne', 'orthopedicMattress', 8, 6, TRUE, 31, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'storage', 'storage', 8, 6, TRUE, 32, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'heating', 'floorHeating', 8, 6, TRUE, 33, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'fridge', 'fridge', 8, 6, TRUE, 34, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'microwave', 'microwave', 8, 6, TRUE, 35, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'coffee', 'coffeeMachine', 8, 6, TRUE, 36, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'dishwasher', 'dishwasher', 8, 6, TRUE, 37, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'television', 'television', 8, 6, TRUE, 38, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'washingmachine', 'washingMachine', 8, 6, TRUE, 39, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'cleaner', 'cleaner', 8, 6, TRUE, 40, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'yardType', 9, 5, FALSE, 41, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'wallHeight', 10, 5, FALSE, 42, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'intercom', 'intercom', 12, 6, TRUE, 43, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'concierge', 'concierge', 12, 6, TRUE, 44, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'guard', 'guard', 12, 6, TRUE, 45, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'gate', 'closedTerritory', 12, 6, TRUE, 46, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'camera', 'camera', 12, 6, TRUE, 47, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'code', 'code', 12, 6, TRUE, 48, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'key', 'personalKey', 12, 6, TRUE, 49, FALSE, FALSE),

       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'typeOffice', 2, 7, FALSE, 1, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'conditionOffice', 2, 8, FALSE, 2, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'businessCenter', 2, 6, FALSE, 10, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'panoramicView', 2, 6, FALSE, 11, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'ownParking', 2, 6, FALSE, 12, FALSE, FALSE),

       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'typeGarage', 2, 7, FALSE, 1, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'stateGarage', 2, 7, FALSE, 2, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'purposeGarage', 2, 7, FALSE, 4, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'heightGarage', 2, 7, FALSE, 5, FALSE, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'parkingSpaces', 2, 7, FALSE, 6, FALSE, FALSE),

       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'roadLang', 2, 7, FALSE, 20, FALSE, FALSE)
;

UPDATE configurations
SET UNIT='M²'
where configurations.NAME = 'area';
UPDATE configurations
SET UNIT='M'
where configurations.NAME = 'wallHeight';
UPDATE configurations
SET UNIT='M'
where id = 94;

INSERT INTO configuration_values ( CREATED_AT, LAST_MODIFIED_AT, VERSION, ICON
                                 , VALUE_TEXT, FK_CONFIGURATION_ID, IS_ICON_LARGE)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'newBuilding', 1, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'secondaryHousing', 1, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'brick', 2, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'panels', 2, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'gasFoamBlock', 2, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'woodFrame', 2, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'other', 2, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'studio', 3, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'adjacent', 3, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'divided', 3, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'multiLevel', 3, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'other', 3, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'oneRoom', 4, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'twoRooms', 4, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'threeRooms', 4, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'fourRooms', 4, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'moreThanFiveRooms', 4, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'totalArea', 5, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'livingArea', 5, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'storeysRange', 6, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'individual', 7, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'central', 7, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'separate', 8, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'compatible', 8, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'notRepaired', 9, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'babusinRepair', 9, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'freshRepair', 9, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'comseticRepair', 9, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'designerRepair', 9, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'needsRepair', 9, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'euroRepair', 9, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'noFurniture', 10, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'oldFurniture', 10, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'newFurniture', 10, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'mixedFurniture', 10, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'onePerson', 'onePerson', 11, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'twoPersons', 'twoPersons', 11, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'family', 'family', 11, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'group', 'group', 11, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'none', 12, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'cat', 'cat', 12, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'dog', 'dog', 12, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'bird', 'otherPet', 12, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'oneMonth', 13, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'twoToSixMonths', 13, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'sixToTwelveMonths', 13, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'moreThanYear', 13, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'calendar', 'asap', 14, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'gym', 'gym', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'restaurant', 'restaurant', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'cart', 'supermarket', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'playground', 'playground', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'school', 'school', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'park', 'park', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'tank', 'water', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'drug', 'drugstore', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'hospital', 'hospital', 19, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'electric', 20, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'gas', 20, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'canal', 20, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'communalPossible', 20, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'external', 43, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'internal', 43, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'toTwoEight', 44, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'toThreeOFive', 44, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'toThreeOTwenty', 44, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'moreThanThreeTwenty', 44, FALSE),

       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'cabinetOffice', 52, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'openSpace', 52, FALSE),

       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'undergroundParking', 57, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'cooperativeGarage', 57, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'parkingSpace', 57, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'separateGarage', 57, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'underCar', 59, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'truck/bus', 59, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'yacht/boat', 59, FALSE),

       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'asphaltRoad', 62, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'dirtRoad', 62, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null, 'noRoad', 62, FALSE),

       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'underConstruction', 'underConstruction', 10, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'commercialLand', 'commercialLand', 10, FALSE),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'agriculturalLand', 'agriculturalLand', 10, FALSE)
;

UPDATE configuration_values
SET ICON_WIDTH = 77
WHERE id = 37;
UPDATE configuration_values
SET ICON_WIDTH = 83
WHERE id = 38;
UPDATE configuration_values
SET ICON_WIDTH = 102
WHERE id = 39;
UPDATE configuration_values
SET ICON_WIDTH = 143
WHERE id = 40;
UPDATE configuration_values
SET VALUE_NUMBER = 1
WHERE value_text = 'oneMonth';
UPDATE configuration_values
SET VALUE_NUMBER = 2
WHERE value_text = 'twoToSixMonths';
UPDATE configuration_values
SET VALUE_NUMBER = 3
WHERE value_text = 'sixToTwelveMonths';
UPDATE configuration_values
SET VALUE_NUMBER = 4
WHERE value_text = 'moreThanYear';

UPDATE configuration_values
SET VALUE_NUMBER = 0
WHERE value_text = 'none';
UPDATE configuration_values
SET VALUE_NUMBER = 6
WHERE value_text = 'cat';
UPDATE configuration_values
SET VALUE_NUMBER = 7
WHERE value_text = 'dog';
UPDATE configuration_values
SET VALUE_NUMBER = 9
WHERE value_text = 'otherPet';

UPDATE configuration_values
SET VALUE_NUMBER = 1
WHERE value_text = 'toTwoEight';
UPDATE configuration_values
SET VALUE_NUMBER = 3
WHERE value_text = 'toThreeOFive';
UPDATE configuration_values
SET VALUE_NUMBER = 5
WHERE value_text = 'toThreeOTwenty';
UPDATE configuration_values
SET VALUE_NUMBER = 7
WHERE value_text = 'moreThanThreeTwenty';

UPDATE configuration_values
SET VALUE_NUMBER = 1
WHERE value_text = 'external';
UPDATE configuration_values
SET VALUE_NUMBER = 4
WHERE value_text = 'internal';



INSERT INTO property_category_configuration (FK_CATEGORY_ID, FK_CONFIGURATION_ID)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9),
       (1, 10),
       (1, 11),
       (1, 12),
       (1, 13),
       (1, 14),
       (1, 15),
       (1, 16),
       (1, 17),
       (1, 18),
       (1, 19),
       (1, 20),
       (1, 21),
       (1, 22),
       (1, 23),
       (1, 24),
       (1, 25),
       (1, 26),
       (1, 27),
       (1, 28),
       (1, 29),
       (1, 30),
       (1, 31),
       (1, 32),
       (1, 33),
       (1, 34),
       (1, 35),
       (1, 36),
       (1, 37),
       (1, 38),
       (1, 39),
       (1, 40),
       (1, 41),
       (1, 42),
       (1, 43),
       (1, 44),
       (1, 45),
       (1, 46),
       (1, 47),
       (1, 48),
       (1, 49),
       (1, 50),

       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (2, 8),
       (2, 9),
       (2, 10),
       (2, 11),
       (2, 12),
       (2, 13),
       (2, 14),
       (2, 15),
       (2, 16),
       (2, 17),
       (2, 18),
       (2, 19),
       (2, 20),
       (2, 21),
       (2, 22),
       (2, 23),
       (2, 24),
       (2, 25),
       (2, 26),
       (2, 27),
       (2, 28),
       (2, 29),
       (2, 30),
       (2, 31),
       (2, 32),
       (2, 33),
       (2, 34),
       (2, 35),
       (2, 36),
       (2, 37),
       (2, 38),
       (2, 39),
       (2, 40),
       (2, 41),
       (2, 42),
       (2, 43),
       (2, 44),
       (2, 45),
       (2, 46),
       (2, 47),
       (2, 48),
       (2, 49),
       (2, 50),

       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (3, 6),
       (3, 7),
       (3, 8),
       (3, 9),
       (3, 10),
       (3, 11),
       (3, 12),
       (3, 13),
       (3, 14),
       (3, 15),
       (3, 16),
       (3, 17),
       (3, 18),
       (3, 19),
       (3, 20),
       (3, 21),
       (3, 22),
       (3, 23),
       (3, 24),
       (3, 25),
       (3, 26),
       (3, 27),
       (3, 28),
       (3, 29),
       (3, 30),
       (3, 31),
       (3, 32),
       (3, 33),
       (3, 34),
       (3, 35),
       (3, 36),
       (3, 37),
       (3, 38),
       (3, 39),
       (3, 40),
       (3, 41),
       (3, 42),
       (3, 43),
       (3, 44),
       (3, 45),
       (3, 46),
       (3, 47),
       (3, 48),
       (3, 49),
       (3, 50),

       (4, 1),
       (4, 2),
       (4, 3),
       (4, 4),
       (4, 5),
       (4, 6),
       (4, 7),
       (4, 8),
       (4, 9),
       (4, 10),
       (4, 11),
       (4, 12),
       (4, 13),
       (4, 14),
       (4, 15),
       (4, 16),
       (4, 17),
       (4, 18),
       (4, 19),
       (4, 20),
       (4, 21),
       (4, 22),
       (4, 23),
       (4, 24),
       (4, 25),
       (4, 26),
       (4, 27),
       (4, 28),
       (4, 29),
       (4, 30),
       (4, 31),
       (4, 32),
       (4, 33),
       (4, 34),
       (4, 35),
       (4, 36),
       (4, 37),
       (4, 38),
       (4, 39),
       (4, 40),
       (4, 41),
       (4, 42),
       (4, 43),
       (4, 44),
       (4, 45),
       (4, 46),
       (4, 47),
       (4, 48),
       (4, 49),
       (4, 50),

       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 5),
       (5, 6),
       (5, 7),
       (5, 8),
       (5, 9),
       (5, 10),
       (5, 11),
       (5, 12),
       (5, 13),
       (5, 14),
       (5, 15),
       (5, 16),
       (5, 17),
       (5, 18),
       (5, 19),
       (5, 20),
       (5, 21),
       (5, 22),
       (5, 23),
       (5, 24),
       (5, 25),
       (5, 26),
       (5, 27),
       (5, 28),
       (5, 29),
       (5, 30),
       (5, 31),
       (5, 32),
       (5, 33),
       (5, 34),
       (5, 35),
       (5, 36),
       (5, 37),
       (5, 38),
       (5, 39),
       (5, 40),
       (5, 41),
       (5, 42),
       (5, 43),
       (5, 44),
       (5, 45),
       (5, 46),
       (5, 47),
       (5, 48),
       (5, 49),
       (5, 50),


       (9, 52),
       (9, 53),
       (9, 5),
       (9, 6),
       (9, 54),
       (9, 55),
       (9, 56),
       (9, 13),
       (9, 14),
       (9, 15),
       (9, 16),

       (7, 57),
       (7, 58),
       (7, 5),
       (7, 59),
       (7, 60),
       (7, 61),
       (7, 13),
       (7, 14),
       (7, 15),
       (7, 16),

       --      (10, 62),(10, 63),(10, 64),(10, 5),    (10, 13),(10, 15),(10, 16),(10, 20),(10, 65)
       (10, 62),
       (10, 5),
       (10, 13),
       (10, 15),
       (10, 16),
       (10, 20)
;



INSERT INTO cities (CREATED_AT, LAST_MODIFIED_AT, VERSION, NAME, ID)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'kyiv', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'odessa', 2),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'kharkiv', 3);

INSERT INTO districts (CREATED_AT, LAST_MODIFIED_AT, VERSION, NAME, CITY_ID)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'borshagivska', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'golosivska', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'darnistki', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'desnianski', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'dniprovski', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'obolonski', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'pecherski', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'podilski', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'sviatoshinksi', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'solomianski', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'troeschina', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'shevchenksi', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'kievsky', 2),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'malinovskyi', 2),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'Primorskyi', 2),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'Suvorovskyi', 2);

INSERT INTO metros (CREATED_AT, LAST_MODIFIED_AT, VERSION, NAME, METRO_LINE, CITY_ID)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'akademmіstechko', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'zhitomirska', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'sviatoshyn', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'nyvky', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'beresteiska', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'shuliavska', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'kpi', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'vokzalna', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'universytet', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'teatralna', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'khreshchatyk', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'arsenalna', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'dnіpro', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'hidropark', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'livoberezhna', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'darnytsia', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'chernihivska', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'lisova', 'red', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'heroivDnipra', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'minska', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'obolon', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'pochaina', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'tarasaShevchenka', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'kontraktovaPloshcha', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'poshtovaPloshcha', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'maidanNezalezhnosti', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ploshchaLvaTolstoho', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'olimpiiska', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'palatsUkraina', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'lybidska', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'demiivska', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'holosiivska', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'vasylkivska', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'vystavkovyiTsentr', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ipodrom', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'teremky', 'blue', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'syrets', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'dorohozhychi', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'lukianivska', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'zolotiVorota', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'palatsSportu', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'klovska', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'pecherska', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'druzhbyNarodiv', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'vydubychi', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'slavutych', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'osokorky', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'pozniaky', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'kharkivska', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'vyrlytsia', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'boryspilska', 'green', 1),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'chervonyKhutir', 'green', 1);
